Repository ddworksAt/oxygencs-grp1-eq4, pull requests merged in 2024-03, with the labels that each got.

#4 [PR] doc modification code source
  README.md
  Wiki/lab2/PostgreSQL.md
Labels: documentation

#2 [PR] Modification du code source
  src/main.py
  test/test.py
Labels: implementation

#6 [ PR] Initialisation of the dockerfile
  Dockerfile
Labels: implementation

#10 [PR] pre commit git hook
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_implementation.yaml
  .github/pull_request_template.md
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  Wiki/lab2/PostgreSQL.md
  Wiki/lab2/gitHookPreCommit.md
  pyproject.toml
  src/main.py
  test/test.py
Labels: implementation

#11 [PR] Bug initialisation dockerfile
  Dockerfile
  Pipfile
  Pipfile.lock
Labels: bug

#13 [PR] Integration continue - OxygenCS
  .github/workflows/main.yml
  Pipfile
  README.md
  Wiki/lab2/IntegrationContinue.md
  Wiki/lab2/gitHookPreCommit.md
  src/main.py
Labels: documentation, implementation

#15 [PR] Bug fix for dockerfile to include dependencies in image
  Dockerfile
Labels: bug
